//! `SpriteId` newtype + build-time registry for the authoring layer (SPEC §3.7, §6.1).
//!
//! `SpriteId` pairs a display name with its `.img.` payload. Two construction
//! paths exist, matching the Path A / Path B asymmetry in SPEC §6.1:
//!
//! - [`SpriteId::lookup`] / [`SpriteId::try_registered`] — zero-alloc access to
//!   sprites harvested from `working-mods/*.txt` at build time. The authoring
//!   layer uses this so a hallucinated sprite name becomes a `None` at the
//!   first callsite (and the surrounding code turns that into an error)
//!   instead of silently emitting garbage.
//! - [`SpriteId::owned`] — unconditional construction from a `(name, img_data)`
//!   pair. The extractor calls this for sprites that are not in the registry.
//!   Making the registry gating would re-break SPEC §3.3 (any valid textmod
//!   must extract) because a new mod with a new sprite could not roundtrip.
//!
//! The `Cow<'static, str>` backing is load-bearing: registry entries are
//! `Cow::Borrowed` and cost nothing to clone; extractor-constructed values are
//! `Cow::Owned`. A plain `&'static str` would be unsound — serde deserialization
//! from an owned `String` has no `'static` lifetime to borrow from.

use std::borrow::Cow;

use serde::{Deserialize, Serialize};

use crate::error::CompilerError;

/// A sprite — display name + `.img.` payload. Fields are private so that every
/// construction path (lookup, owned, serde) flows through this module.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(try_from = "SpriteIdSerde", into = "SpriteIdSerde")]
pub struct SpriteId {
    name: Cow<'static, str>,
    img_data: Cow<'static, str>,
}

/// Flat `{ "name": "...", "img_data": "..." }` JSON shape. `img_data` is not
/// derivable from `name` alone when a consumer's registry doesn't know the
/// sprite, so it must serialize — that's why this isn't a `try_from = "String"`.
#[derive(Serialize, Deserialize, schemars::JsonSchema)]
struct SpriteIdSerde {
    name: String,
    img_data: String,
}

impl From<SpriteId> for SpriteIdSerde {
    fn from(s: SpriteId) -> Self {
        Self {
            name: s.name.into_owned(),
            img_data: s.img_data.into_owned(),
        }
    }
}

impl TryFrom<SpriteIdSerde> for SpriteId {
    type Error = core::convert::Infallible;
    fn try_from(s: SpriteIdSerde) -> Result<Self, Self::Error> {
        Ok(SpriteId {
            name: Cow::Owned(s.name),
            img_data: Cow::Owned(s.img_data),
        })
    }
}

impl SpriteId {
    /// Registry lookup — zero-allocation borrowed value for corpus-known
    /// sprites. Returns `None` for unknown names; callers decide whether to
    /// fall back to [`SpriteId::owned`] (Path A / extractor) or to error out
    /// (Path B / authoring).
    pub fn lookup(name: &str) -> Option<&'static SpriteId> {
        SPRITE_REGISTRY.get(name)
    }

    /// Owned constructor — used by the extractor for sprites not in the
    /// registry so SPEC §3.3 (any valid textmod extracts) is preserved.
    pub fn owned(name: impl Into<String>, img_data: impl Into<String>) -> Self {
        SpriteId {
            name: Cow::Owned(name.into()),
            img_data: Cow::Owned(img_data.into()),
        }
    }

    /// Strict registry-only constructor — errors if `name` is not in the
    /// corpus-derived whitelist. Prefer this over [`SpriteId::lookup`] on
    /// authoring paths where an unknown sprite is a real mistake, not a
    /// novel-sprite extract.
    pub fn try_registered(name: &str) -> Result<&'static SpriteId, CompilerError> {
        Self::lookup(name)
            .ok_or_else(|| CompilerError::sprite_not_found(name.to_string(), None, None))
    }

    /// Display name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Raw `.img.` payload.
    pub fn img_data(&self) -> &str {
        &self.img_data
    }
}

// Generated by `compiler/build.rs`. Emits:
//   pub static SPRITE_REGISTRY: phf::Map<&'static str, SpriteId> = ...;
// Textual inclusion (rather than a submodule) so the generated `SpriteId`
// struct literals can reach the private `name` / `img_data` fields.
include!(concat!(env!("OUT_DIR"), "/sprite_registry_generated.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sprite_owned_roundtrip() {
        let s = SpriteId::owned("X", "abcd");
        assert_eq!(s.name(), "X");
        assert_eq!(s.img_data(), "abcd");
    }

    #[test]
    fn sprite_serde_roundtrip() {
        // Both an owned (novel) sprite and a registry entry must serde-roundtrip.
        // Registry entries become Cow::Owned on deserialize — PartialEq ignores
        // the Cow variant, so equality holds.
        let owned = SpriteId::owned("Foo", "DATA==%");
        let j = serde_json::to_string(&owned).unwrap();
        assert!(j.contains("\"name\":\"Foo\""));
        assert!(j.contains("\"img_data\":\"DATA==%\""));
        let back: SpriteId = serde_json::from_str(&j).unwrap();
        assert_eq!(owned, back);
    }

    #[test]
    fn sprite_lookup_miss() {
        assert!(SpriteId::lookup("NoSuchPokemon").is_none());
    }

    #[test]
    fn sprite_lookup_agumon() {
        // The plan's spec test was `sprite_lookup_charmander`; the
        // Charmander -> Agumon swap is a real Sliceymon+ authoring change,
        // and Agumon is already present in working-mods/sliceymon.txt, so we
        // can pin the test to the final name directly.
        let s = SpriteId::lookup("Agumon")
            .expect("Agumon should be harvested from sliceymon.txt");
        assert_eq!(s.name(), "Agumon");
        assert!(!s.img_data().is_empty());
    }

    #[test]
    fn sprite_try_registered_miss_errors() {
        let err = SpriteId::try_registered("NoSuchPokemon").unwrap_err();
        // SpriteNotFound carries the name so downstream diagnostics can reference it.
        let text = err.to_string();
        assert!(
            text.contains("NoSuchPokemon"),
            "expected error text to name the missing sprite, got: {text}"
        );
    }
}
