//! `SpriteId` newtype + build-time registry for the authoring layer (SPEC §3.7, §6.1).
//!
//! `SpriteId` pairs a display name with its `.img.` payload. Two construction
//! paths exist, matching the Path A / Path B asymmetry in SPEC §6.1:
//!
//! - [`SpriteId::lookup`] / [`SpriteId::try_registered`] — zero-alloc access to
//!   sprites harvested from `working-mods/*.txt` at build time. The **authoring
//!   layer only** uses this so a hallucinated sprite name becomes a `None` at
//!   the first callsite (and the surrounding code turns that into an error)
//!   instead of silently emitting garbage. The extractor must never consult
//!   the registry: the registry is first-write-wins across the 4 reference
//!   mods, so a lookup from extract silently replaces this mod's `.img.`
//!   payload with sliceymon's on any name collision — source corruption,
//!   violating SPEC §3.3.
//! - [`SpriteId::owned`] — unconditional construction from a `(name, img_data)`
//!   pair. The **extractor always** calls this, passing the source's own
//!   `.img.` bytes verbatim. This preserves SPEC §3.3 (any valid textmod must
//!   extract) and keeps `extract(build(extract(mod))) == extract(mod)` honest
//!   at the byte level, not just at IR-equality.
//!
//! The `Cow<'static, str>` backing is load-bearing: registry entries are
//! `Cow::Borrowed` and cost nothing to clone; extractor-constructed values are
//! `Cow::Owned`. A plain `&'static str` would be unsound — serde deserialization
//! from an owned `String` has no `'static` lifetime to borrow from.

use std::borrow::Cow;

use serde::{Deserialize, Serialize};

use crate::error::CompilerError;

/// A sprite — display name + `.img.` payload. Fields are private so that every
/// construction path (lookup, owned, serde) flows through this module.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(try_from = "SpriteIdSerde", into = "SpriteIdSerde")]
pub struct SpriteId {
    name: Cow<'static, str>,
    img_data: Cow<'static, str>,
}

/// Flat `{ "name": "...", "img_data": "..." }` JSON shape. `img_data` is not
/// derivable from `name` alone when a consumer's registry doesn't know the
/// sprite, so it must serialize — that's why this isn't a `try_from = "String"`.
#[derive(Serialize, Deserialize, schemars::JsonSchema)]
struct SpriteIdSerde {
    name: String,
    img_data: String,
}

impl From<SpriteId> for SpriteIdSerde {
    fn from(s: SpriteId) -> Self {
        Self {
            name: s.name.into_owned(),
            img_data: s.img_data.into_owned(),
        }
    }
}

impl TryFrom<SpriteIdSerde> for SpriteId {
    type Error = core::convert::Infallible;
    fn try_from(s: SpriteIdSerde) -> Result<Self, Self::Error> {
        Ok(SpriteId {
            name: Cow::Owned(s.name),
            img_data: Cow::Owned(s.img_data),
        })
    }
}

impl SpriteId {
    /// Registry lookup — zero-allocation borrowed value for corpus-known
    /// sprites. Returns `None` for unknown names; callers decide whether to
    /// fall back to [`SpriteId::owned`] (Path A / extractor) or to error out
    /// (Path B / authoring).
    pub fn lookup(name: &str) -> Option<&'static SpriteId> {
        SPRITE_REGISTRY.get(name)
    }

    /// Owned constructor — used by the extractor for sprites not in the
    /// registry so SPEC §3.3 (any valid textmod extracts) is preserved.
    pub fn owned(name: impl Into<String>, img_data: impl Into<String>) -> Self {
        SpriteId {
            name: Cow::Owned(name.into()),
            img_data: Cow::Owned(img_data.into()),
        }
    }

    /// Strict registry-only constructor — errors if `name` is not in the
    /// corpus-derived whitelist. Prefer this over [`SpriteId::lookup`] on
    /// authoring paths where an unknown sprite is a real mistake, not a
    /// novel-sprite extract.
    pub fn try_registered(name: &str) -> Result<&'static SpriteId, CompilerError> {
        Self::lookup(name)
            .ok_or_else(|| CompilerError::sprite_not_found(name.to_string(), None, None))
    }

    /// Display name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Raw `.img.` payload.
    pub fn img_data(&self) -> &str {
        &self.img_data
    }
}

// Generated by `compiler/build.rs`. Emits:
//   pub static SPRITE_REGISTRY: phf::Map<&'static str, SpriteId> = ...;
// Textual inclusion (rather than a submodule) so the generated `SpriteId`
// struct literals can reach the private `name` / `img_data` fields.
include!(concat!(env!("OUT_DIR"), "/sprite_registry_generated.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sprite_owned_roundtrip() {
        let s = SpriteId::owned("X", "abcd");
        assert_eq!(s.name(), "X");
        assert_eq!(s.img_data(), "abcd");
    }

    #[test]
    fn sprite_serde_roundtrip() {
        // Both an owned (novel) sprite and a registry entry must serde-roundtrip.
        // Registry entries become Cow::Owned on deserialize — PartialEq ignores
        // the Cow variant, so equality holds.
        let owned = SpriteId::owned("Foo", "DATA==%");
        let j = serde_json::to_string(&owned).unwrap();
        assert!(j.contains("\"name\":\"Foo\""));
        assert!(j.contains("\"img_data\":\"DATA==%\""));
        let back: SpriteId = serde_json::from_str(&j).unwrap();
        assert_eq!(owned, back);
    }

    #[test]
    fn sprite_lookup_miss() {
        assert!(SpriteId::lookup("NoSuchPokemon").is_none());
    }

    #[test]
    fn sprite_lookup_agumon() {
        // Plan spec (PLATFORM_FOUNDATIONS_PLAN.md §Chunk 3a): `img_data()` must
        // match `working-mods/sliceymon.txt` byte-for-byte. `Charmander` in the
        // original plan was swapped to `Agumon` (real Sliceymon+ authoring
        // change already present in sliceymon.txt at build time). Load the mod
        // source via `include_str!` and extract Agumon's `.img.` payload at
        // test time — that way a harvester regression in `scan_entity_sprites`
        // would fail this test, not silently relax it.
        let source = include_str!("../../../working-mods/sliceymon.txt");
        let needle = ".n.Agumon";
        let n_pos = source.find(needle).expect("Agumon entity present in sliceymon.txt");
        // Walk backwards to the nearest preceding `.img.` on the same line —
        // the harvester's paired-name rule pins the sprite to its enclosing
        // `(replica...img.DATA)` group.
        let line_start = source[..n_pos].rfind('\n').map(|i| i + 1).unwrap_or(0);
        let img_tag = source[line_start..n_pos]
            .rfind(".img.")
            .expect(".img. precedes .n.Agumon on sliceymon.txt:53");
        let img_start = line_start + img_tag + ".img.".len();
        // Payload terminates at `)` (paren-wrapped group) or the next `.X.` marker.
        let img_end = source[img_start..]
            .find(|c: char| c == ')' || c == '(')
            .map(|o| img_start + o)
            .expect("Agumon `.img.` payload closes with `)` on its line");
        let expected = &source[img_start..img_end];
        assert!(!expected.is_empty(), "test scaffolding bug: empty expected payload");

        let s = SpriteId::lookup("Agumon")
            .expect("Agumon should be harvested from sliceymon.txt");
        assert_eq!(s.name(), "Agumon");
        assert_eq!(
            s.img_data(),
            expected,
            "registry img_data must match sliceymon.txt byte-for-byte",
        );
    }

    #[test]
    fn sprite_try_registered_miss_errors() {
        let err = SpriteId::try_registered("NoSuchPokemon").unwrap_err();
        // SpriteNotFound carries the name so downstream diagnostics can reference it.
        let text = err.to_string();
        assert!(
            text.contains("NoSuchPokemon"),
            "expected error text to name the missing sprite, got: {text}"
        );
    }
}
