//! Build-time I/O shell for the harvester pure core.
//!
//! The pure-core extraction lives in `compiler/src/harvester/mod.rs` and is
//! library-reachable without `std::fs` per SPEC §3.4. This shell reads the
//! corpus from `working-mods/*.txt`, invokes the pure core, assembles the
//! `phf_codegen` sprite-registry static from the pure-core's value-expression
//! triples, and writes the two generated files to `OUT_DIR`. The pure-core
//! and `phf_codegen::Map::build()` machinery are confined here so the
//! library compile of `compiler/src/harvester/` cannot accidentally pull in
//! `phf_codegen` (a build-dependency only).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[path = "src/harvester/mod.rs"]
mod harvester;

/// Fixed corpus scan order — affects doc-comment provenance only (first-seen
/// wins), not correctness. Ordered by authoring authority (primary corpus
/// first).
const WORKING_MOD_ORDER: &[&str] = &[
    "sliceymon.txt",
    "pansaer.txt",
    "punpuns.txt",
    "community.txt",
];

fn main() {
    // Cargo should re-run this script whenever any working-mod changes.
    println!("cargo:rerun-if-changed=build.rs");
    let workspace_root = workspace_root();
    let working_mods_dir = workspace_root.join("working-mods");
    println!(
        "cargo:rerun-if-changed={}",
        working_mods_dir.display()
    );

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let out_dir = Path::new(&out_dir);

    // Single-pass read: both harvesters scan the same file contents, so we
    // read each working-mod exactly once and hand each pass the string it
    // needs. Keeps the build script I/O-cheap and ordered deterministically.
    let mod_contents = read_working_mods(&working_mods_dir);

    let face_id_pairs = harvester::harvest_face_ids(&mod_contents);
    let face_path = out_dir.join("face_id_generated.rs");
    fs::write(&face_path, assemble_face_id_file(&face_id_pairs))
        .unwrap_or_else(|e| panic!("write {}: {}", face_path.display(), e));

    let sprite_triples = harvester::harvest_sprites(&mod_contents);
    let sprite_path = out_dir.join("sprite_registry_generated.rs");
    fs::write(&sprite_path, assemble_sprite_registry_file(&sprite_triples))
        .unwrap_or_else(|e| panic!("write {}: {}", sprite_path.display(), e));
}

/// Read each working-mod exactly once, in the `WORKING_MOD_ORDER` sequence.
/// Missing files are silently skipped so the build doesn't break while a mod
/// is in flux (same policy as the face-id harvester's previous inline loop).
fn read_working_mods(dir: &Path) -> Vec<(&'static str, String)> {
    let mut out = Vec::with_capacity(WORKING_MOD_ORDER.len());
    for mod_name in WORKING_MOD_ORDER {
        let path = dir.join(mod_name);
        if !path.exists() {
            continue;
        }
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
        out.push((*mod_name, contents));
    }
    out
}

/// The compiler/ Cargo.toml lives one level below the repo root. Walk up
/// from CARGO_MANIFEST_DIR to find the `working-mods/` sibling.
fn workspace_root() -> PathBuf {
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo");
    PathBuf::from(manifest_dir)
        .parent()
        .expect("compiler/ must have a parent directory")
        .to_path_buf()
}

/// Assemble `face_id_generated.rs`'s byte content from the pure-core's
/// `(u16-as-string, opaque-text)` pairs.
///
/// Each pair's second element is the per-entry doc-comment + `pub const`
/// block (terminated by its own `\n`); the shell splices it verbatim into
/// the `impl FaceId { ... }` body. The first element is parsed back to
/// `u16` for the `KNOWN_FACE_IDS` slice.
fn assemble_face_id_file(pairs: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by compiler/build.rs — DO NOT EDIT.\n");
    out.push_str("// Harvested from working-mods/*.txt. Determinism: BTreeMap, no I/O side-effects.\n");
    out.push_str("// Consts live inside the `authoring::face_id` module so `FaceId(N)` can\n");
    out.push_str("// access the newtype's private tuple field.\n\n");
    out.push_str("impl FaceId {\n");
    for (_, block) in pairs {
        out.push_str(block);
    }
    out.push_str("}\n\n");

    // Emit a slice of every known FaceID so xref can distinguish Known-vs-
    // Unknown without relying on curated names alone.
    out.push_str("/// Every FaceID harvested from the corpus or curated by name,\n");
    out.push_str("/// in ascending order. Used by the `FaceIdValue::try_new` lookup.\n");
    out.push_str("pub const KNOWN_FACE_IDS: &[u16] = &[\n");
    for (id_str, _) in pairs {
        let _ = writeln!(&mut out, "    {id_str},");
    }
    out.push_str("];\n");
    out
}

/// Assemble `sprite_registry_generated.rs`'s byte content from the pure-
/// core's `(name, value_expr, provenance_suffix)` triples.
///
/// First iteration: feed `(name, value_expr)` into `phf_codegen::Map.entry`
/// so the keys + value-expressions live for the rest of the function (the
/// build crate's `.entry()` signature holds `&str` borrows into `map.build()`).
/// Second iteration: emit the `// Sprite provenance (stable order):` comment
/// block by prefixing `//   <name> ← ` to each provenance suffix.
/// Finally: emit the doc-comments, the `pub static SPRITE_REGISTRY ...`
/// opening, and append `map.build()` followed by `;\n`.
fn assemble_sprite_registry_file(triples: &[(String, String, String)]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by compiler/build.rs — DO NOT EDIT.\n");
    out.push_str("// Harvested from working-mods/*.txt. Determinism: BTreeMap-ordered phf build.\n\n");

    // Build the phf map. Keys + value-expression strings live for the
    // lifetime of `map.build()` because `triples` outlives this function.
    let mut map: phf_codegen::Map<&str> = phf_codegen::Map::new();
    for (name, expr, _) in triples {
        map.entry(name.as_str(), expr.as_str());
    }

    // Provenance block — human-readable, stable across builds because the
    // pure-core's `BTreeMap` iterates in sorted order and `first_seen` is
    // deterministic per-mod-name + per-line.
    out.push_str("// Sprite provenance (stable order):\n");
    for (name, _, provenance_suffix) in triples {
        let _ = writeln!(&mut out, "//   {name} ← {provenance_suffix}");
    }
    out.push('\n');

    out.push_str("/// Corpus-derived sprite registry. Keys are entity display names\n");
    out.push_str("/// (`.mn.` preferred, `.n.` fallback) harvested from `working-mods/*.txt`.\n");
    out.push_str("/// First-write-wins in the `sliceymon > pansaer > punpuns > community` priority order.\n");
    out.push_str("pub static SPRITE_REGISTRY: ::phf::Map<&'static str, SpriteId> = ");
    let _ = write!(&mut out, "{}", map.build());
    out.push_str(";\n");
    out
}
